version: '3'
services:
  agent:
    image: qnib/plain-consul
    hostname: '{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}'
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - 8500:8500
    environment:
      SWARM_TASK_SLOT: "{{.Task.Slot}}"
      SWARM_SERVICE_NAME: "{{.Service.Name}}"
      CONSUL_CLUSTER_IPS: "{{.Service.Name}}"
      CONSUL_BOOTSTRAP_EXPECT: "3"
      CONSUL_SKIP_CURL: "true"
