version: '3'
services:
  agent:
    image: qnib/plain-consul:local6
    hostname: '{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}'
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - 8500:8500
    environment:
      - SWARM_TASK_SLOT={{.Task.Slot}}
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLUSTER_IPS=consul_agent
      - CONSUL_SKIP_CURL=true
